//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScholarshipAppointment.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bills
    {
        public int idBill { get; set; }
        public int idStud { get; set; }
        public string bill { get; set; }
        public Nullable<System.DateTime> finishDate { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
