//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScholarshipAppointment.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bobrovski_4IS1_DataBase_ScholarshipAppointment2Entities : DbContext
    {
        public Bobrovski_4IS1_DataBase_ScholarshipAppointment2Entities()
            : base("name=Bobrovski_4IS1_DataBase_ScholarshipAppointment2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bills> Bills { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrderStrings> OrderStrings { get; set; }
        public virtual DbSet<OrderTypes> OrderTypes { get; set; }
        public virtual DbSet<ScholarshipTypes> ScholarshipTypes { get; set; }
        public virtual DbSet<Specialties> Specialties { get; set; }
        public virtual DbSet<Statements> Statements { get; set; }
        public virtual DbSet<StatementStrings> StatementStrings { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
