//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScholarshipAppointment.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderStrings = new HashSet<OrderStrings>();
        }
    
        public int idOrder { get; set; }
        public int idST { get; set; }
        public int idOT { get; set; }
        public Nullable<System.DateTime> docDate { get; set; }
        public int idUser { get; set; }
        public Nullable<System.DateTime> signDate { get; set; }
        public string comm { get; set; }
    
        public virtual ScholarshipTypes ScholarshipTypes { get; set; }
        public virtual OrderTypes OrderTypes { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderStrings> OrderStrings { get; set; }
    }
}
