//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScholarshipAppointment.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statements
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Statements()
        {
            this.StatementStrings = new HashSet<StatementStrings>();
        }
    
        public int idStat { get; set; }
        public string docNum { get; set; }
        public Nullable<System.DateTime> docDate { get; set; }
        public Nullable<int> monthNum { get; set; }
        public Nullable<int> yearNum { get; set; }
        public Nullable<System.DateTime> signDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatementStrings> StatementStrings { get; set; }
    }
}
