//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScholarshipAppointment.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatementStrings
    {
        public int idSS { get; set; }
        public int idOS { get; set; }
        public int idStat { get; set; }
        public Nullable<decimal> cost { get; set; }
        public string bill { get; set; }
    
        public virtual OrderStrings OrderStrings { get; set; }
        public virtual Statements Statements { get; set; }
    }
}
